//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkipTakeUsingEFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public string ARID_NO { get; set; }
        public string FULL_NAME { get; set; }
        public string CITY { get; set; }
        public string DISCIPLINE { get; set; }
        public Nullable<int> AGE { get; set; }
        public string GENDER { get; set; }
        public Nullable<double> CGPA { get; set; }
    }
}
