//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskVersion2
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentcourse
    {
        public int Sid { get; set; }
        public int Cid { get; set; }
    }
}
